// <auto-generated />
using System;
using AbayaSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbayaSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BoutiqueDbContext))]
    [Migration("20260722205736_AddMultiBranchAndCatalogs")]
    partial class AddMultiBranchAndCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbayaSystem.Core.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWorkshop")
                        .HasColumnType("bit");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("AbayaSystem.Core.Fabric", b =>
                {
                    b.Property<int>("FabricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricId"));

                    b.Property<string>("FabricName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FabricId");

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("AbayaSystem.Core.FabricShop", b =>
                {
                    b.Property<int>("FabricShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricShopId"));

                    b.Property<string>("FabricShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FabricShopId");

                    b.ToTable("FabricShops");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeOfOrder")
                        .HasColumnType("int");

                    b.HasKey("BranchId", "OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("AlterationNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedSupplierId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CutByWorkerId")
                        .HasColumnType("int");

                    b.Property<int?>("FabricId")
                        .HasColumnType("int");

                    b.Property<int?>("FabricShopId")
                        .HasColumnType("int");

                    b.Property<int?>("HandEmbroideredByWorkerId")
                        .HasColumnType("int");

                    b.Property<int>("HybridProcess")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbayaFabricBought")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadyMadeAlteration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSheilaFabricBought")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShopProvidingFabric")
                        .HasColumnType("bit");

                    b.Property<string>("ModelTextDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SelectedSheilaSize")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StitchedByWorkerId")
                        .HasColumnType("int");

                    b.Property<int>("TargetBranchId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("AssignedSupplierId");

                    b.HasIndex("FabricId");

                    b.HasIndex("FabricShopId");

                    b.HasIndex("BranchId", "OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AbayaSystem.Core.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AbayaSystem.Core.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<int>("AssignedRoles")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.HasIndex("BranchId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.HasOne("AbayaSystem.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.HasOne("AbayaSystem.Core.Supplier", "AssignedSupplier")
                        .WithMany()
                        .HasForeignKey("AssignedSupplierId");

                    b.HasOne("AbayaSystem.Core.Fabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId");

                    b.HasOne("AbayaSystem.Core.FabricShop", "FabricShop")
                        .WithMany()
                        .HasForeignKey("FabricShopId");

                    b.HasOne("AbayaSystem.Core.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("BranchId", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSupplier");

                    b.Navigation("Fabric");

                    b.Navigation("FabricShop");
                });

            modelBuilder.Entity("AbayaSystem.Core.Worker", b =>
                {
                    b.HasOne("AbayaSystem.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
