// <auto-generated />
using System;
using AbayaSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbayaSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BoutiqueDbContext))]
    [Migration("20260903223045_AddReadymadeSheila")]
    partial class AddReadymadeSheila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbayaSystem.Core.AbayaSystem.Core.StatusLog", b =>
                {
                    b.Property<int>("StatusLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusLogId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousState")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousWorkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfEvent")
                        .HasColumnType("datetime2");

                    b.HasKey("StatusLogId");

                    b.ToTable("StatusLogs");
                });

            modelBuilder.Entity("AbayaSystem.Core.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWorkshop")
                        .HasColumnType("bit");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("AbayaSystem.Core.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("ButtonType")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("LengthAbayaBack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LengthAbayaFront")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LengthSleeve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfButtons")
                        .HasColumnType("int");

                    b.Property<decimal>("WidthArmHole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WidthBody")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WidthBottom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WidthShoulder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WidthSleeveOpening")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AbayaSystem.Core.ExternalVendorJob", b =>
                {
                    b.Property<int>("ExternalVendorJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalVendorJobId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("DispatchNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DispatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DispatchedByWorkerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivedByWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ExternalVendorJobId");

                    b.HasIndex("ExternalWorkerId");

                    b.HasIndex("BranchId", "OrderId", "OrderItemId");

                    b.ToTable("ExternalVendorJobs");
                });

            modelBuilder.Entity("AbayaSystem.Core.ExternalWorker", b =>
                {
                    b.Property<int>("ExternalWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalWorkerId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportedType")
                        .HasColumnType("int");

                    b.HasKey("ExternalWorkerId");

                    b.ToTable("ExternalWorkers");

                    b.HasData(
                        new
                        {
                            ExternalWorkerId = 1,
                            IsActive = true,
                            Name = "Rubel",
                            Phone = "+971500000001",
                            SupportedType = 2
                        },
                        new
                        {
                            ExternalWorkerId = 2,
                            IsActive = true,
                            Name = "Saiful",
                            Phone = "+971500000002",
                            SupportedType = 2
                        },
                        new
                        {
                            ExternalWorkerId = 3,
                            IsActive = true,
                            Name = "Alim Emb",
                            Phone = "+971500000003",
                            SupportedType = 1
                        },
                        new
                        {
                            ExternalWorkerId = 4,
                            IsActive = true,
                            Name = "Computer Emb1",
                            Phone = "+971500000003",
                            SupportedType = 1
                        },
                        new
                        {
                            ExternalWorkerId = 5,
                            IsActive = true,
                            Name = "Computer Emb2",
                            Phone = "+971500000003",
                            SupportedType = 1
                        });
                });

            modelBuilder.Entity("AbayaSystem.Core.Fabric", b =>
                {
                    b.Property<int>("FabricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricId"));

                    b.Property<string>("FabricName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FabricId");

                    b.ToTable("Fabrics");
                });

            modelBuilder.Entity("AbayaSystem.Core.FabricShop", b =>
                {
                    b.Property<int>("FabricShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricShopId"));

                    b.Property<string>("FabricShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FabricShopId");

                    b.ToTable("FabricShops");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DepositPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BranchId", "OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlterationNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedSupplierId")
                        .HasColumnType("int");

                    b.Property<bool>("BuyFabricForExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CutByWorkerId")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalWorkerId")
                        .HasColumnType("int");

                    b.Property<int?>("FabricId")
                        .HasColumnType("int");

                    b.Property<int?>("FabricShopId")
                        .HasColumnType("int");

                    b.Property<bool>("HandEmbRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("HandEmbroideredByWorkerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbayaFabricBought")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadyMadeAlteration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSheilaFabricBought")
                        .HasColumnType("bit");

                    b.Property<string>("ModelTextDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectedSheilaSize")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StitchedByWorkerId")
                        .HasColumnType("int");

                    b.Property<int>("TargetBranchId")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfOrder")
                        .HasColumnType("int");

                    b.Property<bool>("rawFabricEmb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BranchId", "OrderId", "OrderItemId");

                    b.HasIndex("AssignedSupplierId");

                    b.HasIndex("ExternalWorkerId");

                    b.HasIndex("FabricId");

                    b.HasIndex("FabricShopId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AbayaSystem.Core.SheilaShop", b =>
                {
                    b.Property<int>("SheilaShopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheilaShopID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("SheilaShopName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SheilaShopID");

                    b.HasIndex("BranchID");

                    b.ToTable("SheilaShops", (string)null);
                });

            modelBuilder.Entity("AbayaSystem.Core.SheilaTran", b =>
                {
                    b.Property<int>("SheilaTranID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheilaTranID"));

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SheilaShopID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SheilaTranID");

                    b.HasIndex("SheilaShopID");

                    b.ToTable("SheilaTrans", (string)null);
                });

            modelBuilder.Entity("AbayaSystem.Core.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("AbayaSystem.Core.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<int>("AssignedRoles")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.HasIndex("BranchId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AbayaSystem.Core.ExternalVendorJob", b =>
                {
                    b.HasOne("AbayaSystem.Core.ExternalWorker", "ExternalWorker")
                        .WithMany()
                        .HasForeignKey("ExternalWorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AbayaSystem.Core.OrderItem", "OrderItem")
                        .WithMany("ExternalVendorJobs")
                        .HasForeignKey("BranchId", "OrderId", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalWorker");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.HasOne("AbayaSystem.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbayaSystem.Core.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.HasOne("AbayaSystem.Core.Supplier", "AssignedSupplier")
                        .WithMany()
                        .HasForeignKey("AssignedSupplierId");

                    b.HasOne("AbayaSystem.Core.ExternalWorker", "ExternalWorker")
                        .WithMany()
                        .HasForeignKey("ExternalWorkerId");

                    b.HasOne("AbayaSystem.Core.Fabric", "Fabric")
                        .WithMany()
                        .HasForeignKey("FabricId");

                    b.HasOne("AbayaSystem.Core.FabricShop", "FabricShop")
                        .WithMany()
                        .HasForeignKey("FabricShopId");

                    b.HasOne("AbayaSystem.Core.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("BranchId", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSupplier");

                    b.Navigation("ExternalWorker");

                    b.Navigation("Fabric");

                    b.Navigation("FabricShop");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AbayaSystem.Core.SheilaShop", b =>
                {
                    b.HasOne("AbayaSystem.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AbayaSystem.Core.SheilaTran", b =>
                {
                    b.HasOne("AbayaSystem.Core.SheilaShop", "SheilaShop")
                        .WithMany("Transactions")
                        .HasForeignKey("SheilaShopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheilaShop");
                });

            modelBuilder.Entity("AbayaSystem.Core.Worker", b =>
                {
                    b.HasOne("AbayaSystem.Core.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.Navigation("ExternalVendorJobs");
                });

            modelBuilder.Entity("AbayaSystem.Core.SheilaShop", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
