// <auto-generated />
using System;
using AbayaSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbayaSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BoutiqueDbContext))]
    partial class BoutiqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOrdered")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeOfOrder")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<string>("AlterationNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssignedWorkshopId")
                        .HasColumnType("int");

                    b.Property<int?>("CutByWorkerId")
                        .HasColumnType("int");

                    b.Property<string>("FabricName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAbayaFabricBought")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadyMadeAlteration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSheilaFabricBought")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShopProvidingFabric")
                        .HasColumnType("bit");

                    b.Property<string>("ModelTextDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SelectedSheilaSize")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StitchedByWorkerId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("CutByWorkerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StitchedByWorkerId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AbayaSystem.Core.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<int>("AssignedRoles")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("AbayaSystem.Core.OrderItem", b =>
                {
                    b.HasOne("AbayaSystem.Core.Worker", null)
                        .WithMany()
                        .HasForeignKey("CutByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AbayaSystem.Core.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbayaSystem.Core.Worker", null)
                        .WithMany()
                        .HasForeignKey("StitchedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AbayaSystem.Core.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
